laravel/app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group([
  'namespace' => 'Site'
], function () {

  Route::get('/', ['as' => 'home', 'uses' => 'Home\HomeController@getIndex']);
  Route::post('cadastro-newsletter', ['as' => 'cadastro.newsletter', 'uses' => 'Home\HomeController@postCadastroNewsletter']);

  Route::get('idioma/{sigla_idioma?}', function (Request $request, $sigla_idioma) {
    if ($sigla_idioma == 'pt-br' || $sigla_idioma == 'en' || $sigla_idioma == 'es') {
      Session::put('locale', $sigla_idioma);
      App::setLocale($sigla_idioma);
    }

    return Redirect::back();
  });

  //Rotas temporárias -- RETIRAR DEPOIS DO JOB--
  // Route::get('temp/home', ['as' => 'home', 'uses' => 'Home\HomeController@getIndexTemp']);
  Route::get('temp/nossas-linhas', ['as' => 'nossas-linhas', 'uses' => 'NossasLinhas\NossasLinhasController@getIndexTemp']);
  Route::get('temp/nossas-linhas/{slug_linha}', ['as' => 'nossas-linhas.detalhes', 'uses' => 'NossasLinhas\NossasLinhasController@getIndexTemp']);
  Route::get('temp/nossas-linhas/{slug_linha}/{slug_produto}', ['as' => 'nossas-linhas.detalhes-produto', 'uses' => 'NossasLinhas\NossasLinhasController@getIndexTemp']);
  //Fim da rotas temporárias---------------------  

  Route::get('todos-produtos', ['as' => 'todos-produtos', 'uses' => 'TodosProdutos\TodosProdutosController@getIndex']);
  Route::post('todos-produtos', ['as' => 'busca', 'uses' => 'TodosProdutos\TodosProdutosController@postBusca']);
  Route::get('nossas-linhas', ['as' => 'nossas-linhas', 'uses' => 'NossasLinhas\NossasLinhasController@getIndex']);
  Route::get('nossas-linhas/{slug_linha}', ['as' => 'nossas-linhas.detalhes', 'uses' => 'NossasLinhas\NossasLinhasController@getIndex']);
  Route::get('nossas-linhas/{slug_linha}/{slug_produto}', ['as' => 'nossas-linhas.detalhes-produto', 'uses' => 'NossasLinhas\NossasLinhasController@getIndex']);
  Route::get('a-suavipan', ['as' => 'a-suavipan', 'uses' => 'ASuavipan\ASuavipanController@getIndex']);
  Route::get('contato', ['as' => 'contato', 'uses' => 'Contato\ContatoController@getIndex']);
  Route::post('contato', ['as' => 'contato.enviar', 'uses' => 'Contato\ContatoController@postEnviar']);

  Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
  Route::post('aceite-de-cookies', 'Home\HomeController@postCookies')->name('aceite-de-cookies.post');

  Route::get('descadastro', 'Contato\DescadastrosController@index')->name('descadastros');
  Route::post('descadastro', 'Contato\DescadastrosController@postDescadastro')->name('descadastros.post');
  Route::get('descadastro/confirmacao', 'Contato\DescadastrosController@indexConfirmacao')->name('descadastros.confirmacao');
});

// Authentication routes
Route::get('painel/auth/login', ['as' => 'painel.login', 'uses' => 'Painel\Auth\AuthController@getLogin']);
Route::post('painel/auth/login', ['as' => 'painel.auth', 'uses' => 'Painel\Auth\AuthController@postLogin']);
Route::get('painel/auth/logout', ['as' => 'painel.logout', 'uses' => 'Painel\Auth\AuthController@getLogout']);

Route::group([
  'middleware' => 'auth',
  'namespace' => 'Painel',
  'prefix' => 'painel'
], function () {

  Route::get('/', ['as' => 'painel.dashboard', 'uses' => function () {
    return view('painel.dashboard.index');
  }]);

  Route::post('gravar-ordem-registros', function (Illuminate\Http\Request $request) {
    $itens = $request->input('data');
    $tabela = $request->input('tabela');
    for ($i = 0; $i < count($itens); $i++)
      DB::table($tabela)->where('id', $itens[$i])->update(array('ordem' => $i));
  });


  Route::resource('usuarios', 'Usuarios\UsuariosController');
  Route::resource('linhas', 'Linhas\LinhasController');

  Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
  Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
  // Route::get('painel/linhas', ['as' => 'painel.linhas','uses' => 'Painel\Linhas\LinhasController@getIndex']);

  //  Route::get('linhas', ['as' => 'painel.linhas.index', 'uses' => 'Linhas\LinhasController@getIndex']);

  // CONTEÚDOS SEPARADOS
  // Route::get('conteudos', ['as' => 'painel.conteudos.index', 'uses' => 'Conteudos\ConteudosController@getIndex']);
  // Route::post('conteudos', ['as' => 'painel.conteudos.update', 'uses' => 'Conteudos\ConteudosController@postUpdate']);
  Route::get('conteudos/home', ['as' => 'painel.home.index', 'uses' => 'Conteudos\ConteudosController@indexHome']);
  Route::post('conteudos/home', ['as' => 'painel.home.update', 'uses' => 'Conteudos\ConteudosController@updateHome']);
  Route::get('conteudos/todos-os-produtos', ['as' => 'painel.todos-os-produtos.index', 'uses' => 'Conteudos\ConteudosController@indexProdutos']);
  Route::post('conteudos/todos-os-produtos', ['as' => 'painel.todos-os-produtos.update', 'uses' => 'Conteudos\ConteudosController@updateProdutos']);
  Route::get('conteudos/nossas-linhas', ['as' => 'painel.nossas-linhas.index', 'uses' => 'Conteudos\ConteudosController@indexLinhas']);
  Route::post('conteudos/nossas-linhas', ['as' => 'painel.nossas-linhas.update', 'uses' => 'Conteudos\ConteudosController@updateLinhas']);
  Route::get('conteudos/a-suavipan', ['as' => 'painel.a-suavipan.index', 'uses' => 'Conteudos\ConteudosController@indexSuavipan']);
  Route::post('conteudos/a-suavipan', ['as' => 'painel.a-suavipan.update', 'uses' => 'Conteudos\ConteudosController@updateSuavipan']);
  Route::get('conteudos/contato', ['as' => 'painel.contato.index', 'uses' => 'Conteudos\ConteudosController@indexContato']);
  Route::post('conteudos/contato', ['as' => 'painel.contato.update', 'uses' => 'Conteudos\ConteudosController@updateContato']);

  //Route::resource('linhas', 'Linhas\LinhasController', ['only' => ['index', 'create', 'edit', 'update']]);
  Route::resource('tipos', 'Tipos\TiposController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);
  Route::resource('produtos', 'Produtos\ProdutosController', ['only' => ['index', 'create', 'store', 'edit', 'update', 'destroy']]);
  
  Route::get('cadastros/download', ['as' => 'painel.cadastros.download', 'uses' => 'Cadastros\CadastrosController@getDownload']);
  Route::resource('cadastros', 'Cadastros\CadastrosController', ['only' => ['index', 'destroy']]);

  Route::get('descadastros/download', 'Cadastros\DescadastrosController@getDownload')->name('painel.descadastros.download');
  Route::resource('descadastros', 'Cadastros\DescadastrosController', ['only' => ['index', 'destroy']]);

  // NOVAS ROTAS DO PAINEL:

});

laravel/app/Http/Controllers/Painel/Produtos/ProdutosController.php
<?php

namespace Suavipan\Http\Controllers\Painel\Produtos;

use Illuminate\Http\Request;
use Suavipan\Http\Controllers\Controller;

use Suavipan\Libs\Thumbs;
use Suavipan\Models\Tipo;
use Suavipan\Models\Linha;
use Suavipan\Models\Produto;


class ProdutosController extends Controller{

	public function index(Request $request)
	{
    $linha = Linha::findOrFail($request->linha_id);
    $tipo = Tipo::findOrFail($request->tipo_id);
		return view('painel.produtos.index')->with(compact('linha', 'tipo'));
	}
	
	public function create(Request $request)
	{
	    $linha = Linha::findOrFail($request->linha_id);
	    $tipo = Tipo::findOrFail($request->tipo_id);
		return view('painel.produtos.create')->with(compact('linha', 'tipo'));
	}
	
		public function store(Request $request)
	{
		$this->validate($request, [
			'titulo_pt'       => 'required'
  	]);

		$object = new Produto;
		
		$object->linhas_id = $request->linhas_id;
		
		$object->tipos_id = $request->tipos_id;

		$object->titulo_pt = $request->titulo_pt;
		$object->titulo_en = $request->titulo_en;
		$object->titulo_es = $request->titulo_es;
		$object->ingredientes_pt = $request->ingredientes_pt;
		$object->ingredientes_en = $request->ingredientes_en;
		$object->ingredientes_es = $request->ingredientes_es;
		$object->tabela_porcao_pt = $request->tabela_porcao_pt;
		$object->tabela_porcao_en = $request->tabela_porcao_en;
		$object->tabela_porcao_es = $request->tabela_porcao_es;
		$object->nutri_valor_calorico = $request->nutri_valor_calorico;
		$object->nutri_valor_calorico_pct = $request->nutri_valor_calorico_pct;
		$object->nutri_carboidratos = $request->nutri_carboidratos;
		$object->nutri_carboidratos_pct = $request->nutri_carboidratos_pct;
		$object->nutri_proteinas = $request->nutri_proteinas;
		$object->nutri_proteinas_pct = $request->nutri_proteinas_pct;
		$object->nutri_gorduras_totais = $request->nutri_gorduras_totais;
		$object->nutri_gorduras_totais_pct = $request->nutri_gorduras_totais_pct;
		$object->nutri_gorduras_saturadas = $request->nutri_gorduras_saturadas;
		$object->nutri_gorduras_saturadas_pct = $request->nutri_gorduras_saturadas_pct;
		$object->nutri_gorduras_trans = $request->nutri_gorduras_trans;
		$object->nutri_gorduras_trans_pct = $request->nutri_gorduras_trans_pct;
		$object->nutri_fibra_alimentar = $request->nutri_fibra_alimentar;
		$object->nutri_fibra_alimentar_pct = $request->nutri_fibra_alimentar_pct;
		$object->nutri_sodio = $request->nutri_sodio;
		$object->nutri_sodio_pct = $request->nutri_sodio_pct;

		$imagem = Thumbs::make($request, 'imagem', null, null, 'produtos/');
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Produto criado com sucesso.');

			return redirect()->route('painel.produtos.index', ['linha_id' => $object->linhas_id, 'tipo_id' => $object->tipos_id]);

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao criar Produto! ('.$e->getMessage().')'));

		}
	}

	public function edit($id)
	{
		$registro = Produto::find($id);
		return view('painel.produtos.edit')->with(compact('registro'));
	}

	public function update(Request $request, $id)
	{
		$this->validate($request, [
			'titulo_pt'       => 'required'
  	]);

		$object = Produto::find($id);

		$object->titulo_pt = $request->titulo_pt;
		$object->titulo_en = $request->titulo_en;
		$object->titulo_es = $request->titulo_es;
		$object->ingredientes_pt = $request->ingredientes_pt;
		$object->ingredientes_en = $request->ingredientes_en;
		$object->ingredientes_es = $request->ingredientes_es;
		$object->tabela_porcao_pt = $request->tabela_porcao_pt;
		$object->tabela_porcao_en = $request->tabela_porcao_en;
		$object->tabela_porcao_es = $request->tabela_porcao_es;
		$object->nutri_valor_calorico = $request->nutri_valor_calorico;
		$object->nutri_valor_calorico_pct = $request->nutri_valor_calorico_pct;
		$object->nutri_carboidratos = $request->nutri_carboidratos;
		$object->nutri_carboidratos_pct = $request->nutri_carboidratos_pct;
		$object->nutri_proteinas = $request->nutri_proteinas;
		$object->nutri_proteinas_pct = $request->nutri_proteinas_pct;
		$object->nutri_gorduras_totais = $request->nutri_gorduras_totais;
		$object->nutri_gorduras_totais_pct = $request->nutri_gorduras_totais_pct;
		$object->nutri_gorduras_saturadas = $request->nutri_gorduras_saturadas;
		$object->nutri_gorduras_saturadas_pct = $request->nutri_gorduras_saturadas_pct;
		$object->nutri_gorduras_trans = $request->nutri_gorduras_trans;
		$object->nutri_gorduras_trans_pct = $request->nutri_gorduras_trans_pct;
		$object->nutri_fibra_alimentar = $request->nutri_fibra_alimentar;
		$object->nutri_fibra_alimentar_pct = $request->nutri_fibra_alimentar_pct;
		$object->nutri_sodio = $request->nutri_sodio;
		$object->nutri_sodio_pct = $request->nutri_sodio_pct;

		$imagem = Thumbs::make($request, 'imagem', null, null, 'produtos/');
		if($imagem) $object->imagem = $imagem;

		try {

			$object->save();

			$request->session()->flash('sucesso', 'Produto alterado com sucesso.');

			return redirect()->route('painel.produtos.index', ['linha_id' => $object->linhas_id, 'tipo_id' => $object->tipos_id]);

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao alterar Produto! ('.$e->getMessage().')'));

		}
	}

	public function destroy(Request $request, $id)
	{
		$object = Produto::find($id);

		$linha_id = $object->linhas_id;
		$tipo_id = $object->tipos_id;

		$object->delete();

		$request->session()->flash('sucesso', 'Produto removido com sucesso.');

		return redirect()->route('painel.produtos.index', ['linha_id' => $linha_id, 'tipo_id' => $tipo_id]);
	}

}

laravel/app/Http/Controllers/PainelOld/Cadastros/CadastrosController.php
<?php

namespace Suavipan\Http\Controllers\Painel\Cadastros;

use Illuminate\Http\Request;
use Suavipan\Http\Controllers\Controller;

use Suavipan\Models\CadastroNewsletter;

class CadastrosController extends Controller{

	public function index(Request $request)
	{
    return view('painel.cadastros.index')->with(['registros' => CadastroNewsletter::all()]);
	}

  public function getDownload(Request $request)
  {
    $registros = CadastroNewsletter::all();

    $filename = 'Cadastros_Newsletter_'.date('d_m_Y');

    $registrosArray = [];

    foreach ($registros as $key => $value) {
      $registrosArray[$key]['nome'] = $value->nome;
      $registrosArray[$key]['email'] = $value->email;
      $registrosArray[$key]['data de cadastro'] = $value->created_at->format('d/m/Y H:i');
    }

    \Excel::create($filename, function($excel) use($registrosArray) {
	    $excel->sheet('Relatório de Cadastros', function($sheet) use ($registrosArray) {
	      $sheet->fromArray($registrosArray);
	    });
		})->download('xls');
  }

  public function destroy(Request $request, $id)
	{
		$object = CadastroNewsletter::find($id);
		$object->delete();

		$request->session()->flash('sucesso', 'Cadastro removido com sucesso.');

		return redirect()->route('painel.cadastros.index');
	}

}

laravel/app/Http/Controllers/PainelOld/Conteudos/ConteudosController.php
<?php

namespace Suavipan\Http\Controllers\Painel\Conteudos;

use Illuminate\Http\Request;
use Suavipan\Http\Controllers\Controller;
use View;
use Hash;
use DB;

use Suavipan\Libs\Thumbs;
use Suavipan\Models\Conteudo;

class ConteudosController extends Controller{

	public function getIndex()
	{
		return view('painel.conteudos.index')->with(['registros' => Conteudo::all()]);
	}

	public function postUpdate(Request $request)
	{
		$conteudos = $request->conteudos;
    foreach($conteudos as $indice => $valores){
      foreach($valores as $campo => $valor){
        $conteudo = Conteudo::indice($indice)->first();
        $conteudo->{$campo} = $valor;
        $conteudo->save();
      }
    }

		$arquivos = $request->arquivos;

		foreach($arquivos as $indice => $imagem){
			if($imagem){
				$filename = $imagem->getClientOriginalName();
				$conteudo = Conteudo::indice($indice)->first();
				$imagem->move('assets/img/conteudos', $filename);
				$conteudo->valor_pt_br = $filename;
				$conteudo->save();
			}
    }

		try {

			$request->session()->flash('sucesso', 'Conteúdo alterado com sucesso.');

			return redirect()->route('painel.conteudos.index');

		} catch (\Exception $e) {

			$request->flash();

			return back()->withErrors(array('Erro ao alterar conteúdo! ('.$e->getMessage().')'));

		}
	}

}

laravel/app/Http/Controllers/PainelOld/Site/ASuavipan/ASuavipanController.php
<?php

namespace Suavipan\Http\Controllers\Site\ASuavipan;

use Illuminate\Http\Request;
use Suavipan\Http\Controllers\Controller;

class ASuavipanController extends Controller
{

  public function getIndex(Request $request)
  {
    return view('site.a-suavipan.index');
  }

}

laravel/app/Http/Controllers/PainelOld/Site/Contato/ContatoController.php
<?php

namespace Suavipan\Http\Controllers\Site\Contato;

use Illuminate\Http\Request;
use Suavipan\Http\Controllers\Controller;
use Mail;

class ContatoController extends Controller
{

  public function getIndex(Request $request)
  {
    return view('site.contato.index');
  }


  public function postEnviar(Request $request)
  {
    $this->validate($request, [
      'nome' => 'required',
      'email' => 'required|email',
      'mensagem' => 'required'
    ]);

    $data['nome'] = $request->input('nome');
    $data['email'] = $request->input('email');
    $data['telefone'] = $request->input('telefone');
    $data['mensagem'] = $request->input('mensagem');

    Mail::send('emails.contato', $data, function($message) use ($data)
    {
      $message->to('contato@suavipan.com.br')
              ->subject('Contato via site - '.$data['nome'])
              ->bcc('bruno@trupe.net')
              ->replyTo($data['email'], $data['nome']);
    });


    $request->session()->flash('contato_enviado', true);

    return redirect()->route('contato');
  }
}

laravel/app/Http/Controllers/PainelOld/Site/Home/HomeController.php
<?php

namespace Suavipan\Http\Controllers\Site\Home;

use Illuminate\Http\Request;
use Suavipan\Http\Controllers\Controller;

use View;

use Suavipan\Models\Linha;
use Suavipan\Models\CadastroNewsletter;

class HomeController extends Controller
{

  public function getIndex(Request $request)
  {
    return view('site.home.index');
  }

  public function postCadastroNewsletter(Request $request)
  {
    $this->validate($request, [
      'newsletter.nome'  => 'required',
      'newsletter.email' => 'required|email'
    ]);

    $cadastro = CadastroNewsletter::create($request->newsletter);

    $request->session()->flash('newsletter_sucesso', true);
    return redirect()->back();
  }

}

laravel/resources/views/painelOld/produtos/create.blade.php
@extends('painel.template')

@section('conteudo')

  <div class="container-fluid padded-bottom">
  	<div class="row">
  		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-4">

        <h2>Linha: {{$registro->linha->titulo_pt}}</h2>

        <h2>Tipo: {{$registro->tipo->titulo_pt}}</h2>

        <h3>Editar Produto</h3>

        <hr>

        <a href="{{URL::route('painel.produtos.index', ['linha_id' => $registro->linhas_id, 'tipo_id' => $registro->tipos_id])}}" class="btn btn-default">&larr; voltar</a>

		    <hr>

		    @include('painel.partials.mensagens')

		    <form action="{{ URL::route('painel.produtos.update', $registro->id) }}" method="post" enctype="multipart/form-data">

					<input type="hidden" name="_method" value="PUT">

					{!! csrf_field() !!}

			  	<div class="form-group">
					  <label>Título em Português</label>
						<input type="text" class="form-control" name="titulo_pt" value="{{ $registro->titulo_pt }}" required>
					</div>
          <div class="form-group">
					  <label>Título em Inglês</label>
						<input type="text" class="form-control" name="titulo_en" value="{{ $registro->titulo_en }}">
					</div>
          <div class="form-group">
					  <label>Título em Espanhol</label>
						<input type="text" class="form-control" name="titulo_es" value="{{ $registro->titulo_es }}">
					</div>

					<hr>

          <div class="form-group">
            @if($registro->imagem)
              Imagem atual<br>
              <img src="assets/img/produtos/{{$registro->imagem}}"><br>
            @endif
            <label>Alterar Imagem</label>
            <input type="file" class="form-control" name="imagem">
          </div>

          <hr>

          <div class="form-group">
					  <label>Ingredientes em Português</label>
						<textarea class="form-control" name="ingredientes_pt">{{ $registro->ingredientes_pt }}</textarea>
					</div>
          <div class="form-group">
					  <label>Ingredientes em Inglês</label>
						<textarea class="form-control" name="ingredientes_en">{{ $registro->ingredientes_en }}</textarea>
					</div>
          <div class="form-group">
					  <label>Ingredientes em Espanhol</label>
						<textarea class="form-control" name="ingredientes_es">{{ $registro->ingredientes_es }}</textarea>
					</div>

          <hr>

          <div class="form-group">
					  <label>Porção para a tabela nutricional em Português</label>
						<input type="text" class="form-control" name="tabela_porcao_pt" value="{{ $registro->tabela_porcao_pt }}">
					</div>
          <div class="form-group">
					  <label>Porção para a tabela nutricional em Inglês</label>
						<input type="text" class="form-control" name="tabela_porcao_en" value="{{ $registro->tabela_porcao_en }}">
					</div>
          <div class="form-group">
					  <label>Porção para a tabela nutricional em Espanhol</label>
						<input type="text" class="form-control" name="tabela_porcao_es" value="{{ $registro->tabela_porcao_es }}">
					</div>

          <hr>

          <table class="tabela-nutricional">
            <thead>
              <tr>
                <td colspan="3">Tabela Nutricional</td>
              </tr>
              <tr>
                <td></td>
                <td>
                  Quantidade
                </td>
                <td>
                  % Valor Diário
                </td>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Valor Calórico</td>
                <td>
                  <input type="text" name="nutri_valor_calorico" value="{{$registro->nutri_valor_calorico}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_valor_calorico_pct" value="{{$registro->nutri_valor_calorico_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Carboidratos</td>
                <td>
                  <input type="text" name="nutri_carboidratos" value="{{$registro->nutri_carboidratos}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_carboidratos_pct" value="{{$registro->nutri_carboidratos_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Proteínas</td>
                <td>
                  <input type="text" name="nutri_proteinas" value="{{$registro->nutri_proteinas}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_proteinas_pct" value="{{$registro->nutri_proteinas_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Gorduras Totais</td>
                <td>
                  <input type="text" name="nutri_gorduras_totais" value="{{$registro->nutri_gorduras_totais}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_gorduras_totais_pct" value="{{$registro->nutri_gorduras_totais_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Gorduras Saturadas</td>
                <td>
                  <input type="text" name="nutri_gorduras_saturadas" value="{{$registro->nutri_gorduras_saturadas}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_gorduras_saturadas_pct" value="{{$registro->nutri_gorduras_saturadas_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Gorduras trans</td>
                <td>
                  <input type="text" name="nutri_gorduras_trans" value="{{$registro->nutri_gorduras_trans}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_gorduras_trans_pct" value="{{$registro->nutri_gorduras_trans_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Fibra Alimentar</td>
                <td>
                  <input type="text" name="nutri_fibra_alimentar" value="{{$registro->nutri_fibra_alimentar}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_fibra_alimentar_pct" value="{{$registro->nutri_fibra_alimentar_pct}}" class="form-control">
                </td>
              </tr>
              <tr>
                <td>Sódio</td>
                <td>
                  <input type="text" name="nutri_sodio" value="{{$registro->nutri_sodio}}" class="form-control">
                </td>
                <td>
                  <input type="text" name="nutri_sodio_pct" value="{{$registro->nutri_sodio_pct}}" class="form-control">
                </td>
              </tr>
            </tbody>
          </table>

          <hr>

					<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

					<a href="{{ URL::route('painel.produtos.index', ['linha_id' => $registro->linhas_id, 'tipo_id' => $registro->tipos_id])}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

				</form>

      </div>
		</div>
  </div>

@endsection

laravel/resources/views/painelOld/produtos/index.blade.php
@extends('painel.template')

@section('conteudo')

<div class="container-fluid padded-bottom">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <h2>Linha: {{$linha->titulo_pt}}</h2>

      <h2>Tipo: {{$tipo->titulo_pt}}</h2>

      <h3>Produtos</h3>

      <hr>

      <a href="{{URL::route('painel.tipos.index', ['linha_id' => $linha->id])}}" class="btn btn-default">&larr; voltar</a>

      <hr>

      @include('painel.partials.mensagens')

      <table class="table table-striped table-bordered table-hover">

        <thead>
          <tr>
            <th>Título</th>
            <th><span class="glyphicon glyphicon-cog"></span></th>
          </tr>
        </thead>

        <tbody>
          @foreach ($tipo->produtos as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
              <td>{{ $registro->titulo_pt }}</td>
              <td class="crud-actions">
                <a href="{{ URL::route('painel.produtos.edit', $registro->id ) }}" class="btn btn-primary btn-sm">editar</a>

                <form action="{{ URL::route('painel.produtos.destroy', $registro->id) }}" method="post">
                  {!! csrf_field() !!}
                  <input type="hidden" name="_method" value="DELETE">
                  <button type="submit" class="btn btn-danger btn-sm btn-delete">excluir</button>
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>

      </table>
    </div>
  </div>
</div>

@endsection